development:
    adapter: postgresql
    encoding: utf8
    database: fuse_development
    username: CHANGE_ME
    password: CHANGE_ME
    host: 127.0.0.1
    port: 5432
    pool: 25

test:
    adapter: postgresql
    encoding: utf8
    database: fuse_test
    username: CHANGE_ME
    password: CHANGE_ME
    host: 127.0.0.1
    port: 5432

production:
    adapter: postgresql
    encoding: utf8
    database: fuse_production
    username: CHANGE_ME
    password: CHANGE_ME
    host: localhost
    pool: 25